### ISSUE TITLE
Password error

### ISSUE THREAD

**Issue by xuV2** [yancie-yjr/scd.github.io#6]
Hi @panwangaz  Baidu online disk always prompts password error, or can you send the data set to my mailbox？ 2712726205@qq.com

**Comment by liuqinglong110** [comment]
You can use Google Drive link.

**Comment by liuqinglong110** [comment]
> Hi @panwangaz Baidu online disk always prompts password error, or can you send the data set to my mailbox？ [2712726205@qq.com](mailto:2712726205@qq.com)

Me too.  Are you successfully downloading the dataset now?

**Comment by liuqinglong110** [comment]
![图片](https://user-images.githubusercontent.com/23652342/221801554-487b9bdb-0ead-43dd-ac09-8a4270657cb2.png)

At the time of the last submission, the author only modified the network disk path, but did not change the password. In fact, the original path can be downloaded.

OSCD can be downloaded through Google Cloud Disk, only 1.5G.

The other two Baidu network disk addresses can be replaced with the following content respectively, and the corresponding password remains unchanged.

https://pan.baidu.com/s/18BaUM3SI8q9JSwE9NBGzXw     password: uqr5  

https://pan.baidu.com/share/init?surl=v6EBudDAWimywoWPGw2--A   password: 56b5

**Comment by yancie-yjr** [comment]
We have updated the password
