### ISSUE TITLE
dataset split: train, validation and test?

### ISSUE THREAD

**Issue by antoine-avek** [yancie-yjr/scd.github.io#7]
hello,
First thank you for making the dataset available to public for educational purposes.
I have used LSCD+OSCD 1 label with the training and validation split proposed in the zip files in this depo.
Using Azure ML and yolov5 existing model, a model could be training achieving the following metrics:

Log loss
Min: 1.2727, Max: 2.5639, Last: 1.2727
log_loss_train
Min: 1.2509, Max: 2.6741, Last: 1.2509
Mean average precision
Min: 0.89987, Max: 0.95319, Last: **0.95041**
precision
Min: 0.62281, Max: 0.84570, Last: 0.84570
recall
Min: 0.94030, Max: 0.96451, Last: 0.96101

I was wondering if a test dataset existed, that could use to advise on the final accuracy of the model after completing the training phase.

Many thanks

Antoine

**Comment by yancie-yjr** [comment]
we do not build a test set, you can split one for testing.
